// Code generated by "spawner "; DO NOT EDIT.

package inner

type factory func() interface{}

func Spawner(name string, newPool ...bool) (interface{}, bool) {
	f, ok := spawner[name]
	if !ok {
		return nil, ok
	}
	return f(), true
}

func Put(name string, x interface{}) {}

var spawner = map[string]factory{
	"inner.LoginRoleInfo":      func() interface{} { return &LoginRoleInfo{} },
	"inner.Account":            func() interface{} { return &Account{} },
	"inner.SetMemberRsp":       func() interface{} { return &SetMemberRsp{} },
	"inner.SetMemberReq":       func() interface{} { return &SetMemberReq{} },
	"inner.Error":              func() interface{} { return &Error{} },
	"inner.Ok":                 func() interface{} { return &Ok{} },
	"inner.GateMsgWrapper":     func() interface{} { return &GateMsgWrapper{} },
	"inner.PlayerInfo":         func() interface{} { return &PlayerInfo{} },
	"inner.KickOutReq":         func() interface{} { return &KickOutReq{} },
	"inner.PullPlayer":         func() interface{} { return &PullPlayer{} },
	"inner.BindSessionWithRID": func() interface{} { return &BindSessionWithRID{} },
	"inner.OfflineNtf":         func() interface{} { return &OfflineNtf{} },
	"inner.KickOutRsp":         func() interface{} { return &KickOutRsp{} },
	"inner.GSessionClosed":     func() interface{} { return &GSessionClosed{} },
	"inner.OnlineNtf":          func() interface{} { return &OnlineNtf{} },
	"inner.RoleInfo":           func() interface{} { return &RoleInfo{} },
	"inner.Mail":               func() interface{} { return &Mail{} },
	"inner.AllianceInfo":       func() interface{} { return &AllianceInfo{} },
	"inner.MailInfo":           func() interface{} { return &MailInfo{} },
}
