// Code generated by "spawner "; DO NOT EDIT.

package inner

type factory func() interface{}

func Spawner(name string, newPool ...bool) (interface{}, bool) {
	f, ok := spawner[name]
	if !ok {
		return nil, ok
	}
	return f(), true
}

func Put(name string, x interface{}) {}

var spawner = map[string]factory{
	"inner.Account":               func() interface{} { return &Account{} },
	"inner.MemberInfoOnLoginRsp":  func() interface{} { return &MemberInfoOnLoginRsp{} },
	"inner.MemberInfoOnLoginReq":  func() interface{} { return &MemberInfoOnLoginReq{} },
	"inner.AddMemberRsp":          func() interface{} { return &AddMemberRsp{} },
	"inner.SetMemberPositionReq":  func() interface{} { return &SetMemberPositionReq{} },
	"inner.MemberInfoOnLogoutReq": func() interface{} { return &MemberInfoOnLogoutReq{} },
	"inner.CreateAllianceRsp":     func() interface{} { return &CreateAllianceRsp{} },
	"inner.SetMemberPositionRsp":  func() interface{} { return &SetMemberPositionRsp{} },
	"inner.AddMemberReq":          func() interface{} { return &AddMemberReq{} },
	"inner.CreateAllianceReq":     func() interface{} { return &CreateAllianceReq{} },
	"inner.NewPlayerInfo":         func() interface{} { return &NewPlayerInfo{} },
	"inner.Error":                 func() interface{} { return &Error{} },
	"inner.PullPlayer":            func() interface{} { return &PullPlayer{} },
	"inner.PlayerInfo":            func() interface{} { return &PlayerInfo{} },
	"inner.Ok":                    func() interface{} { return &Ok{} },
	"inner.GateMsgWrapper":        func() interface{} { return &GateMsgWrapper{} },
	"inner.BindSessionWithRID":    func() interface{} { return &BindSessionWithRID{} },
	"inner.KickOutRsp":            func() interface{} { return &KickOutRsp{} },
	"inner.KickOutReq":            func() interface{} { return &KickOutReq{} },
	"inner.GSessionClosed":        func() interface{} { return &GSessionClosed{} },
	"inner.Mail":                  func() interface{} { return &Mail{} },
	"inner.MailInfo":              func() interface{} { return &MailInfo{} },
	"inner.RoleInfo":              func() interface{} { return &RoleInfo{} },
	"inner.AllianceInfo":          func() interface{} { return &AllianceInfo{} },
}
