[base]
dispaly    = "true"
logpath    = "./log"
etcdprefix = "/actor/"
etcdaddr   = "127.0.0.1:2379"


# 网关
[server]
    [server.login_1]
        actoraddr  = "127.0.0.1:8100"
        mysql      = "root:starunion@tcp(127.0.0.1:3306)/%s?charset=utf8mb4&parseTime=True&loc=Local"
        luapath    = "./root/servers/gate/lua/main.lua"
        database   = "game"
        configjson = "../server/config/confjson"

    [server.gateway_1]
        actoraddr = "127.0.0.1:8001"
        gateaddr  = "0.0.0.0:9001"     # client连接端口

    [server.gateway_2]
        actoraddr = "127.0.0.1:8002"
        gateaddr  = "0.0.0.0:9002"     # client连接端口

    [server.game_1]
        actoraddr  = "127.0.0.1:8201"
        mysql      = "root:starunion@tcp(127.0.0.1:3306)/%s?charset=utf8mb4&parseTime=True&loc=Local"
        database   = "game"
        configjson = "../server/config/confjson"


    [server.all_1]
        actoraddr  = "127.0.0.1:8000"
        gateaddr   = "0.0.0.0:9001"
        mysql      = "root:starunion@tcp(127.0.0.1:3306)/%s?charset=utf8mb4&parseTime=True&loc=Local"
        database   = "game"
        configjson = "../server/config/confjson"

    [server.client_1]
        actoraddr  = "127.0.0.1:5001"
    [server.client_2]
        actoraddr  = "127.0.0.1:5002"
    [server.client_3]
        actoraddr  = "127.0.0.1:5003"