// Code generated by excelExport. DO NOT EDIT.
// source. 测试4.xlsx

package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
)

// array and map
var _Test4Map = map[int64]*Test4{}
var _Test4Array = []*Test4{}

type Test4 struct {
	data *_Test4
}

// 类型结构

type _Test4 struct {
	Id     int64       // ID
	Test1  string      // 测试字段1
	Test2  int64       // 者是个
	Test4  int2int     // 飞机我
	Test5  int2str     // 分解为
	Test6  str2int     // 附件
	Test7  str2str     // 夫君
	Test8  array_int   // 额外i吧
	Test9  array_str   // 非飞机
	Test10 float32     // 飞机我附件二
	Test11 array_float // 附件
}

//ID
func (c *Test4) Id() int64 { return c.data.Id }

// 测试字段1
func (c *Test4) Test1() string { return c.data.Test1 }

// 者是个
func (c *Test4) Test2() int64 { return c.data.Test2 }

// 飞机我
func (c *Test4) LenTest4() int                                { return c.data.Test4.Len() }
func (c *Test4) Test4(key int64) (int64, bool)                { return c.data.Test4.Get(key) }
func (c *Test4) RangeTest4(fn func(int64, int64) (stop bool)) { c.data.Test4.Range(fn) }
func (c *Test4) CopyTest4() int2int                           { return c.data.Test4.Copy() }

// 分解为
func (c *Test4) LenTest5() int                                 { return c.data.Test5.Len() }
func (c *Test4) Test5(key int64) (string, bool)                { return c.data.Test5.Get(key) }
func (c *Test4) RangeTest5(fn func(int64, string) (stop bool)) { c.data.Test5.Range(fn) }
func (c *Test4) CopyTest5() int2str                            { return c.data.Test5.Copy() }

// 附件
func (c *Test4) LenTest6() int                                 { return c.data.Test6.Len() }
func (c *Test4) Test6(key string) (int64, bool)                { return c.data.Test6.Get(key) }
func (c *Test4) RangeTest6(fn func(string, int64) (stop bool)) { c.data.Test6.Range(fn) }
func (c *Test4) CopyTest6() str2int                            { return c.data.Test6.Copy() }

// 夫君
func (c *Test4) LenTest7() int                                  { return c.data.Test7.Len() }
func (c *Test4) Test7(key string) (string, bool)                { return c.data.Test7.Get(key) }
func (c *Test4) RangeTest7(fn func(string, string) (stop bool)) { c.data.Test7.Range(fn) }
func (c *Test4) CopyTest7() str2str                             { return c.data.Test7.Copy() }

// 额外i吧
func (c *Test4) LenTest8() int                              { return c.data.Test8.Len() }
func (c *Test4) Test8(key int) (int64, bool)                { return c.data.Test8.Get(key) }
func (c *Test4) RangeTest8(fn func(int, int64) (stop bool)) { c.data.Test8.Range(fn) }
func (c *Test4) CopyTest8() array_int                       { return c.data.Test8.Copy() }

// 非飞机
func (c *Test4) LenTest9() int                               { return c.data.Test9.Len() }
func (c *Test4) Test9(key int) (string, bool)                { return c.data.Test9.Get(key) }
func (c *Test4) RangeTest9(fn func(int, string) (stop bool)) { c.data.Test9.Range(fn) }
func (c *Test4) CopyTest9() array_str                        { return c.data.Test9.Copy() }

// 飞机我附件二
func (c *Test4) Test10() float32 { return c.data.Test10 }

// 附件
func (c *Test4) LenTest11() int                                { return c.data.Test11.Len() }
func (c *Test4) Test11(key int) (float32, bool)                { return c.data.Test11.Get(key) }
func (c *Test4) RangeTest11(fn func(int, float32) (stop bool)) { c.data.Test11.Range(fn) }
func (c *Test4) CopyTest11() array_float                       { return c.data.Test11.Copy() }

func HasTest4(key int64) bool {
	_, ok := _Test4Map[key]
	return ok
}

func GetTest4(key int64) *Test4 {
	return _Test4Map[key]
}

func RangeTest4(fn func(i int, row *Test4) (stop bool)) {
	for i, row := range _Test4Array {
		if fn(i, row) {
			break
		}
	}
}

func LenTest4() int { return len(_Test4Array) }

func init() {
	loadFn["Test4"] = loadTest4
}

func loadTest4(dir string) error {
	data, err := os.ReadFile(path.Join(dir, "Test4.json"))
	if err != nil {
		return fmt.Errorf("file=%v read err=%v", err.Error())
	}

	datas := []*_Test4{}
	err = json.Unmarshal(data, &datas)
	if err != nil {
		return fmt.Errorf("file=%v parse err=%v", err.Error())
	}

	result_array := make([]*Test4, 0, len(datas))
	result_map := make(map[int64]*Test4, len(datas))
	for _, row := range datas {
		data := &Test4{data: row}
		result_array = append(result_array, data)
		result_map[row.Id] = data
	}
	_Test4Array = result_array
	_Test4Map = result_map
	fmt.Printf("%-50v len:%v\n", "Test4 load finish! ", len(result_array))
	return nil
}
