package common

import (
	"fmt"
	"testing"
)

func TestGZip(t *testing.T) {
	testData := []byte(
		`ABCDEFGHIJfjiewofjiewofjewiofjewiofjewiofjewiofjewiofjewiofjewofjew
		FJEWIOFJEWIOFJEWIOFJEWIOFJEWIOFJEWOIFJEWIOFJEWIOFJWEOIFJEWOIFJEWIOFJ
		FJEIOWFJEWIOFJEWIOFJEWIOFJEWOIFJEWIOFJEWIFOEWJFIOEWJFIOEWJFWEOIFWEIO
		VNREIGHREIGHREIWOGHREIOGHREIJWOGHREIWUOGHREUIWGHREUIWOGHRUIEWOGHRUEI
		VHUREOWTYRQPTFEUWOPFHDISVBNUERIWOGNVUIRONVURIEOGHRUEIWGHOREUITUQIOBN
		FJEWIOFJEWIOFJEWIOFJEWIOFJEWIOFJEWOIFJEWIOFJEWIOFJWEOIFJEWOIFJEWIOFJ
		FJEIOWFJEWIOFJEWIOFJEWIOFJEWOIFJEWIOFJEWIFOEWJFIOEWJFIOEWJFWEOIFWEIO
		VNREIGHREIGHREIWOGHREIOGHREIJWOGHREIWUOGHREUIWGHREUIWOGHRUIEWOGHRUEI
		"KLMN，这是测试数据`)
	fmt.Println("data size", len(testData))
	compress, _ := GZip(testData)
	fmt.Println(compress)
	fmt.Println("compress size", len(compress))
	data, _ := UnGZip(compress)
	fmt.Println(string(data))
}
