// Code generated by "spawner -pool=false"; DO NOT EDIT.

package outer

type factory func() interface{}

func Spawner(name string, newPool ...bool) (interface{}, bool) {
	f, ok := spawner[name]
	if !ok {
		return nil, ok
	}
	return f(), true
}

func Put(name string, x interface{}) {}

var spawner = map[string]factory{
	"outer.AgentMembersReq":    func() interface{} { return &AgentMembersReq{} },
	"outer.AgentMembersRsp":    func() interface{} { return &AgentMembersRsp{} },
	"outer.Base":               func() interface{} { return &Base{} },
	"outer.PlayerInfo":         func() interface{} { return &PlayerInfo{} },
	"outer.FailRsp":            func() interface{} { return &FailRsp{} },
	"outer.Unknown":            func() interface{} { return &Unknown{} },
	"outer.SetRoleInfoReq":     func() interface{} { return &SetRoleInfoReq{} },
	"outer.BindPhoneRsp":       func() interface{} { return &BindPhoneRsp{} },
	"outer.ModifyPasswordRsp":  func() interface{} { return &ModifyPasswordRsp{} },
	"outer.SetRoleInfoRsp":     func() interface{} { return &SetRoleInfoRsp{} },
	"outer.ModifyPasswordReq":  func() interface{} { return &ModifyPasswordReq{} },
	"outer.BindPhoneReq":       func() interface{} { return &BindPhoneReq{} },
	"outer.HeartRsp":           func() interface{} { return &HeartRsp{} },
	"outer.LoginRsp":           func() interface{} { return &LoginRsp{} },
	"outer.RoleInfo":           func() interface{} { return &RoleInfo{} },
	"outer.HeartReq":           func() interface{} { return &HeartReq{} },
	"outer.LoginReq":           func() interface{} { return &LoginReq{} },
	"outer.EnterGameRsp":       func() interface{} { return &EnterGameRsp{} },
	"outer.EnterGameReq":       func() interface{} { return &EnterGameReq{} },
	"outer.ReceiveMailItemRsp": func() interface{} { return &ReceiveMailItemRsp{} },
	"outer.ReceiveMailItemReq": func() interface{} { return &ReceiveMailItemReq{} },
	"outer.ReadMailRsp":        func() interface{} { return &ReadMailRsp{} },
	"outer.DeleteMailReq":      func() interface{} { return &DeleteMailReq{} },
	"outer.Mail":               func() interface{} { return &Mail{} },
	"outer.MailInfo":           func() interface{} { return &MailInfo{} },
	"outer.MailListReq":        func() interface{} { return &MailListReq{} },
	"outer.ReadMailReq":        func() interface{} { return &ReadMailReq{} },
	"outer.MailListRsp":        func() interface{} { return &MailListRsp{} },
	"outer.AddMailNotify":      func() interface{} { return &AddMailNotify{} },
}
