version: '3.8'

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    #volumes:
    #  - ./db/mongo:/bitnami/mongodb
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    #volumes:
    #  - ./db/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
    restart: always


  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    restart: always

  dog:
    image: wwj32/dog:latest
    container_name: dog
    volumes: 
      - ./config.json:/app/config.json
    restart: always
